"""Build a simplified Laurentia outline for the reconstruction widget.

Reads the Whitmeyer & Karlstrom (2007) Laurentia GIS polygons from the
sibling Laurentia_Paleogeography repository (read-only), dissolves them
into continental landmasses, simplifies the result, and writes
laurentia_outline.js for laurentia_reconstruction.html.

Run in the ess-jbook environment:
    mamba activate ess-jbook
    python build_laurentia_outline.py
"""

import json
from pathlib import Path

import numpy as np
import shapefile
from shapely.geometry import Polygon
from shapely.ops import unary_union

SRC = (Path("/Users/penokean/0000_GitHub/Laurentia_Paleogeography")
       / "Data" / "Whitmeyer2007_GIS" / "Laurentia.shp")
OUT = Path(__file__).resolve().parent / "laurentia_outline.js"

MIN_AREA = 1.0        # square degrees; drops the smallest Arctic islets
SIMPLIFY = 0.22       # degrees; Douglas-Peucker tolerance

# Greenland blocks in the Whitmeyer & Karlstrom (2007) compilation as
# extended for Greenland after St-Onge et al. (2009)
GREENLAND_PLATE_IDS = {10018, 10028, 10032, 10036, 10568}

# Closure of Greenland to North America, undoing Labrador Sea / Baffin Bay
# opening so the pre-rift fit is restored before the ca. 1096 Ma
# paleomagnetic reconstruction is applied.
GREENLAND_EULER = (67.5, -118.5, -13.8)      # pole lat, pole lon, angle (deg)


def rotate_lonlat(coords, pole_lat, pole_lon, angle):
    """Rotate [(lon, lat), ...] about an Euler pole by `angle` degrees."""
    la, lo = np.radians(pole_lat), np.radians(pole_lon)
    k = np.array([np.cos(la) * np.cos(lo), np.cos(la) * np.sin(lo), np.sin(la)])
    a = np.radians(angle)
    lon = np.radians([c[0] for c in coords])
    lat = np.radians([c[1] for c in coords])
    v = np.stack([np.cos(lat) * np.cos(lon), np.cos(lat) * np.sin(lon), np.sin(lat)])
    # Rodrigues' rotation formula, applied column-wise
    kv = k @ v
    out = (v * np.cos(a)
           + np.cross(k, v, axisb=0).T * np.sin(a)
           + k[:, None] * kv * (1 - np.cos(a)))
    return list(zip(np.degrees(np.arctan2(out[1], out[0])),
                    np.degrees(np.arcsin(np.clip(out[2], -1, 1)))))


def main():
    sf = shapefile.Reader(str(SRC))
    rings, n_greenland = [], 0
    for rec, sh in zip(sf.records(), sf.shapes()):
        if sh.shapeType == 0 or not sh.points:
            continue
        is_greenland = rec["PLATE_ID"] in GREENLAND_PLATE_IDS
        n_greenland += is_greenland
        parts = list(sh.parts) + [len(sh.points)]
        for i in range(len(parts) - 1):
            ring = sh.points[parts[i]:parts[i + 1]]
            if len(ring) < 4:
                continue
            if is_greenland:
                ring = rotate_lonlat(ring, *GREENLAND_EULER)
            poly = Polygon(ring)
            if not poly.is_valid:
                poly = poly.buffer(0)
            if not poly.is_empty:
                rings.append(poly)
    print(f"{n_greenland} Greenland shapes closed with Euler pole "
          f"{GREENLAND_EULER[0]}N, {GREENLAND_EULER[1]}E, {GREENLAND_EULER[2]}°")

    dissolved = unary_union(rings)
    polys = list(dissolved.geoms) if dissolved.geom_type == "MultiPolygon" else [dissolved]
    polys = sorted((p for p in polys if p.area >= MIN_AREA), key=lambda p: -p.area)

    out, total = [], 0
    for poly in polys:
        simple = poly.simplify(SIMPLIFY, preserve_topology=True)
        if simple.is_empty:
            continue
        # a simplified polygon can split; keep every piece
        pieces = list(simple.geoms) if simple.geom_type == "MultiPolygon" else [simple]
        for piece in pieces:
            coords = [[round(x, 3), round(y, 3)] for x, y in piece.exterior.coords]
            if len(coords) < 4:
                continue
            out.append(coords)
            total += len(coords)

    OUT.write_text(
        "/* Laurentia outline, dissolved and simplified from the\n"
        " * Whitmeyer & Karlstrom (2007) GIS compilation.\n"
        " * Generated by build_laurentia_outline.py -- do not edit by hand.\n"
        " * Each entry is a closed ring of [longitude, latitude] pairs. */\n"
        "const LAURENTIA_OUTLINE = "
        + json.dumps(out, separators=(",", ":"))
        + ";\n")
    print(f"{len(out)} rings, {total} vertices -> {OUT} "
          f"({OUT.stat().st_size / 1024:.0f} kB)")


if __name__ == "__main__":
    main()
